### ISSUE TITLE
"Power Words"

### ISSUE THREAD

**Issue by BradKML** [wooorm/buzzwords#24]
- https://standout-cv.com/power-words-for-cv
- https://zety.com/blog/resume-action-words
- https://www.themuse.com/advice/185-powerful-verbs-that-will-make-your-resume-awesome
- https://www.indeed.com/career-advice/resumes-cover-letters/resume-power-words
- https://novoresume.com/career-blog/top-10-most-powerful-action-words-for-resume
- https://www.jobscan.co/blog/resume-action-words/

**Comment by wooorm** [comment]
PR welcome!
