### ISSUE TITLE
Buzzword List Dumping

### ISSUE THREAD

**Issue by BradKML** [wooorm/buzzwords#25]
- https://www.amanet.org/articles/80-business-buzzwords-now-and-then/
- https://www.pointsincase.com/lists/corporate-buzzwords-redefined-for-work-at-home-times
- https://andrewessa.com/2020/08/11/119-worst-business-buzzwords-for-2020/
- https://topsourcetalentllc.com/60-business-buzzwords-to-delete-from-your-vocabulary/
- https://www.platformexecutive.com/news/blog/the-120-most-annoying-business-phrases-and-buzzwords-in-2021/
- https://www.thompsonwriting.com/business-buzzwords
- https://www.trustradius.com/buyer-blog/119-hated-business-buzzwords
- https://www.psychologytoday.com/us/blog/tame-your-terrible-office-tyrant/201603/75-corporate-buzzwords-and-phrases-drive-us-crazy

**Comment by wooorm** [comment]
Are you interested in working on these?

**Comment by wooorm** [comment]
PR welcome!
