### ISSUE TITLE
Does not work with TypeScript 4.5 that also uses ESM

### ISSUE THREAD

**Issue by HyperCrowd** [wooorm/buzzwords#26]
Importing the simple array of strings this module has with:

`import { buzzwords } from 'buzzwords'`

provides the following error:

`Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`

tsconfig.json is

```
{
  "compilerOptions": {
    "outDir": "./build/",
    "strictNullChecks": true,
    "noImplicitAny": true,
    "module": "commonjs",
    "target": "es5",
    "lib": [ "es2021" ],
    "jsx": "react",
    "allowJs": true,
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "esModuleInterop": true,
    "sourceMap": true
  }
}
```

Start command is:

`ts-node-dev -r esm --respawn --transpile-only index.js`

Side note: importing a simple array should not be this hard :(

**Comment by wooorm** [comment]
See https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c and `ts-node`’s readme on how to set up ESM.
